In [17]:
#Genetic algo to solve simple equation
import numpy as np
n = 6
chromosome = np.random.randint(0, 30 ,(n,4))
print("Chromosomes :",chromosome)

epoch = 0
while epoch <  10 :

    objective = abs(30 - chromosome[:,0] - 2*chromosome[:,1] -3*chromosome[:,2] -
                    4*chromosome[:,3] ) # - fitness object:
    fitness =  1/(1 + objective)
    total = fitness.sum()
    prob = fitness/total # - probability
    cum_sum = np.cumsum(prob) # - cumulative sum
    Ran_nums = np.random.random((chromosome.shape[0])) # - random numbers
    
    # new matrix of chromosome:
    chromosome_2 = np.zeros((chromosome.shape[0],4))   
    for i in range(Ran_nums.shape[0]):
        for j in range(chromosome.shape[0]):
            if Ran_nums[i]  < cum_sum[j]:
                chromosome_2[i,:] = chromosome[j,:]
                break        
    chromosome = chromosome_2
    #print("Chromosomes after updation :",chromosome)
        
    R = [np.random.random() for i in range(n)] # - random values
    pc = 0.25
    flag = Ran_nums < pc # - flagged values
    cross_chromosome = chromosome[[(i == True) for i in flag]]
    len_cross_chrom = len(cross_chromosome)
    cross_values = np.random.randint(1,3,len_cross_chrom)
    cpy_chromosome = np.zeros(cross_chromosome.shape)
    
    for i in range(cross_chromosome.shape[0]):
        cpy_chromosome[i , :] = cross_chromosome[i , :]
        
    if len_cross_chrom == 1:
        cross_chromosome = cross_chromosome
    else :
        for i in range(len_cross_chrom):
            c_val = cross_values[i]
            if i == len_cross_chrom - 1 :
                cross_chromosome[i , c_val:] = cpy_chromosome[0 , c_val:]
            else :
                cross_chromosome[i , c_val:] = cpy_chromosome[i+1 , c_val:]
    
    index_chromosome = 0
    index_newchromosome = 0
    for i in flag :
        if i == True :
            chromosome[index_chromosome, :] = cross_chromosome[index_newchromosome, :]
            index_newchromosome = index_newchromosome + 1
        index_chromosome = index_chromosome + 1 

    print("New chromosomes:\n", chromosome)
    
    a, b = chromosome.shape[0], chromosome.shape[1]
    total_gen = a*b
    print("Total generations:\n",total_gen)

    pm = 0.1 # - mutation rate
    no_of_mutations = int(np.round(pm * total_gen))
    print("Number of mutations:\n", no_of_mutations)

    gen_num = np.random.randint(0, total_gen - 1, no_of_mutations)
    print("Generated rand numbers:\n" , gen_num)
    
    Replacing_num = np.random.randint(0, 30, no_of_mutations)
    print("Number's replace:\n" , Replacing_num)
    
    for i in range(no_of_mutations):
        a = gen_num[i]
        row = a//4
        col = a%4
        chromosome[row , col] = Replacing_num[i]
    
    print("Chromosomes after mutation:\n" , chromosome)
    epoch = epoch + 1

Chromosomes : [[20 21 26 15]
 [27 11 18 12]
 [10 24 16 11]
 [20 18 22 15]
 [19  0  8  1]
 [ 1 26 26 25]]
New chromosomes:
 [[19.  0.  8.  1.]
 [10. 24. 16. 11.]
 [19.  0.  8.  1.]
 [20. 18. 22. 15.]
 [19.  0.  8.  1.]
 [19.  0.  8.  1.]]
Total generations:
 24
Number of mutations:
 2
Generated rand numbers:
 [7 5]
Number's replace:
 [24 27]
Chromosomes after mutation:
 [[19.  0.  8.  1.]
 [10. 27. 16. 24.]
 [19.  0.  8.  1.]
 [20. 18. 22. 15.]
 [19.  0.  8.  1.]
 [19.  0.  8.  1.]]
New chromosomes:
 [[19.  0.  8.  1.]
 [19.  0.  8.  1.]
 [19.  0.  8.  1.]
 [10. 27. 16. 24.]
 [19.  0.  8.  1.]
 [19.  0.  8.  1.]]
Total generations:
 24
Number of mutations:
 2
Generated rand numbers:
 [8 8]
Number's replace:
 [14  8]
Chromosomes after mutation:
 [[19.  0.  8.  1.]
 [19.  0.  8.  1.]
 [ 8.  0.  8.  1.]
 [10. 27. 16. 24.]
 [19.  0.  8.  1.]
 [19.  0.  8.  1.]]
New chromosomes:
 [[19.  0.  8.  1.]
 [19.  0.  8.  1.]
 [ 8.  0.  8.  1.]
 [19.  0.  8.  1.]
 [19.  0.  8.  1.]
 [19.  0.  8.  1.]